server:
  port: 8001
spring:
  application:
    name: provider-ticket
eureka:
  instance:
    prefer-ip-address: true #注册服务的时候使用ip地址
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
