spring:
  application:
    name: consumer-user
server:
  port: 8080

eureka:
  instance:
    prefer-ip-address: true #注册服务的时候使用ip地址
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
