server:
  port: 8761
eureka:
  instance:
    appname: eureka-service #eureka实例的主机名
  client:
    register-with-eureka: false #不将自己注册到eureka
    fetch-registry: false #不从eureka上获取注册信息
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
